name: Remove old artifacts

on:
  schedule:
    # Every day at 12pm UTC
    - cron: '0 0 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 week'
        # Optional inputs
        # skip-tags: true
        # skip-recent: 5
