# This is a basic workflow to help you get started with Actions

name: Unity Build CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.4.8f1

      # Build
      - name: Unity - Builder
        uses: webbertakken/unity-builder@v1.4
        with:
          unityVersion: 2019.4.8f1
          targetPlatform: iOS # Android

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
